FROM node:5.5-wheezy
# https://github.com/nodejs/docker-node/blob/master/5.5/wheezy/Dockerfile

# https://github.com/Yelp/dumb-init
RUN wget --quiet https://github.com/Yelp/dumb-init/releases/download/v1.0.0/dumb-init_1.0.0_amd64.deb
RUN dpkg -i dumb-init_*.deb
RUN npm set progress=false

EXPOSE 8000

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY source/ .
COPY abzu_config.json app/config/config.json
RUN npm install

CMD [ "dumb-init", "npm", "start" ]
