FROM node:6.3
# https://hub.docker.com/_/node/

# https://github.com/Yelp/dumb-init
RUN wget --quiet https://github.com/Yelp/dumb-init/releases/download/v1.0.0/dumb-init_1.0.0_amd64.deb
RUN dpkg -i dumb-init_*.deb
RUN npm set progress=false

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY source/ .

RUN npm install
RUN npm build

EXPOSE 8000
ENV port 8000

CMD [ "dumb-init", "npm", "run", "prod" ]
