name: Base deploy workflow
on:
  workflow_call:
    inputs:
      env_name: { required: true, type: string }
      favicon: { required: true, type: string }
      config: { required: true, type: string }
      firebase_secret: { required: true, type: string }
      project: { required: true, type: string }
      target: { required: true, type: string }

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          name: build
          path: build
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy favicon
        run: cp .github/environments/${{ inputs.favicon }} build/favicon.ico
      - name: Copy bootstrap config
        run: cp .github/environments/${{ inputs.config }} build/bootstrap.json
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets[inputs.firebase_secret] }}
          channelId: live
          projectId: ${{ inputs.project }}
          target: ${{ inputs.target }}
