name: Staging maintenance mode
on: workflow_dispatch
jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    environment: 'staging'
    steps:
      - uses: actions/checkout@v4
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v6
      - name: Copy maintenance mode file
        run: mkdir build && cp public/maintenance.html build/index.html
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ENT_ROR_ABZU_TST }}'
          channelId: live
          projectId: ent-ror-abzu-tst

